### PR TITLE
Add support for Valorless's HavenElytra

### PR DESCRIPTION
**Pull request by bonn2**
This is effectively a copy paste of my previous implementation for pim16aap's ArmoredElytra, with the only major differences being where exactly the data is scraped from.

### CODE REVIEW

**Comment by mrmelon54** [comment]
I should probably merge this already

**Comment by bonn2** [comment]
I mean, I'm not your dad. Do what you want.

**Comment by mrmelon54** [comment]
Can you send a link to Valorless's HavenElytra

**Comment by bonn2** [comment]
https://www.spigotmc.org/resources/havenelytra-combined-chestplates-and-elytras.109583/

It also depends on

https://www.spigotmc.org/resources/valorlessutils-1-18-1-20-4.109586/

**Comment by mrmelon54** [comment]
Ok so I did some refactoring, can you update the PR to work this those changes?

**Comment by bonn2** [comment]
That should be it. I've done some quick testing and it all seems to be working exactly as it did before the refactor.

(Side-note that refactor is actually quite nice, so much less duped code)

**Comment by bonn2** [comment]
Alright, now I'm ready. I just noticed that none of the other records used @ Override so I figured I'd remove it to be more consistent. It doesn't change anything anyways in this context.

**Comment by bonn2** [comment]
(I realize I am pretty much frantically talking to myself here.)
I just noticed that the armor doesn't show enchantment glint while equipped, and I'm not seeing this implemented anywhere else in the other records. I tried copying the enchantment data to both the elytra and the chestplate but that only shows enchants in the inventory. Could you shed some light on how this is supposed to be handled, or if it maybe got missed?

**Comment by mrmelon54** [comment]
You definitely aren't talking to yourself, I do read all the comments

**Comment by bonn2** [comment]
There we are, refactored ~~again~~

**Comment by bonn2** [comment]
All caught up

**Comment by mrmelon54** [comment]
awesome

**Pull request merged**
